name: recdat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0-1.0.dev <4.0.0"

dependencies:
  cloud_firestore: ^4.17.5
  firebase_app_check: ^0.2.2+7
  firebase_auth: ^4.20.0
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  google_nav_bar: ^5.0.6
  multi_select_flutter: ^4.1.3
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.4.0
  timezone: ^0.9.3
  flutter_typeahead: ^5.2.0
  file_picker: ^8.0.3
  flutter_pdfview: ^1.3.2
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
